# Generated by Django 3.2.12 on 2022-05-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruploadimage',
            old_name='UserUploadImage',
            new_name='profile_image',
        ),
    ]
