# Generated by Django 3.2.12 on 2022-05-19 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile_path', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=100, null=True)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_id', to='movies.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile_path', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('overview', models.TextField(null=True)),
                ('released_date', models.DateField(null=True)),
                ('vote_avg', models.FloatField(null=True)),
                ('tagline', models.TextField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('runtime', models.IntegerField(blank=True, default=120, null=True)),
                ('trailer_youtube_key', models.TextField(null=True)),
                ('poster_path', models.TextField(null=True)),
                ('adult', models.BooleanField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('movie_similar', models.JSONField(blank=True)),
                ('actors', models.ManyToManyField(related_name='movies', through='movies.Characters', to='movies.Actor')),
                ('director', models.ManyToManyField(related_name='movies', to='movies.Director')),
                ('genre_ids', models.ManyToManyField(related_name='movies', to='movies.Genres')),
                ('like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('spoiler', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_users', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movies.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCountry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_name', to='movies.productioncountry')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_name', to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieCountry', to='movies.ProductionCountry'),
        ),
        migrations.AddField(
            model_name='characters',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_id', to='movies.movie'),
        ),
    ]
